name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: windows-latest
    environment: kiran
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        $accessKeyId: ${{secrets.AWS_ACCESS_KEY_ID}}
        $secretAccessKey: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: |
         powershell.exe ./movefile.ps1 $accessKeyId $secretAccessKey
      shell: pwsh
