name: Push directory to another repository
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - name: Clone repository
      run: |
        git clone https://github.com/kondekiran/backend.git
        git config --global user.name "konde kiran"
        git config --global user.email "kondekiran9292@gmail.com"

        
      # replace with appropriate AWS command to clone the repo

    - name: Run script file
      run: |
        ./git.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $AWS_REGION
      # replace with appropriate AWS command to execute your script
      
