$env:SOURCE_REPO_URL = "https://github.com/kondekiran/backend.git"
$env:DEST_REPO_URL = "https://github.com/kondekiran/frantend.git"
$env:SOURCE_BRANCH = "master"
$env:DEST_BRANCH = "master"

# Clone source repository
git clone $env:SOURCE_REPO_URL
cd backend
git config --global user.name "kondekiran"
git config --global user.email "kondekiran9292@gmail.com"
git checkout $env:SOURCE_BRANCH

# Clone destination repository
git clone $env:DEST_REPO_URL
cd frantend
git config --global user.name "kondekiran"
git config --global user.email "kondekiran9292@gmail.com"
git checkout $env:DEST_BRANCH

# Copy directory
Copy-Item -Path "backend\directory-to-push" -Destination "frantend\directory-to-push" -Recurse

# Commit and push changes
cd frantend
git add .
git commit -m "Pushed directory from source repository"
git push origin $env:DEST_BRANCH


